---
- name: install packages
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{base_packages}}"

- name: remove packages
  apt:
    name: "{{item}}"
    state: absent
  with_items: "{{base_remove_packages}}"
