---
- include: install.yml
  tags:
    - base
    - install
    - base-install

- include: users.yml
  with_items: "{{base_users}}"
  tags:
    - users
    - install
    - users-install

- include: directories.yml
  with_items: "{{base_directories}}"
  tags:
    - directories
    - install
    - directories-install