version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=splitweb.fr
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redthinkdb:
    image: rethinkdb:latest
    ports:
      - "8080:8080"
      - "28015:28015"
