version: "2"

services:
  nginx-proxy:
    image: antoinehumbert/nginx-proxy:1.0
    container_name: nginx-proxy
    network_mode: "host"
    environment:
      - DEFAULT_HOST=163.172.182.154
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redthinkdb:
    image: rethinkdb:latest
    ports:
      - "8080:8080"
      - "28015:28015"
